//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagmentSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public enum Status { New, In_Progress, Finshed }
    public partial class Task
    {
        [Browsable(false)]
        public int TaskID { get; set; }
        public string ProjectCode { get; set; }
        public string Assignee { get; set; }
        [DisplayName("Status")]
        public Status StatusTemp { get; set; }
        [Browsable(false)]
        public Nullable<int> Status { get; set; }
        [Browsable(false)]
        public Nullable<decimal> Progress { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Description { get; set; }
        [Browsable(false)]
        public virtual Project Project { get; set; }
        [Browsable(false)]
        public virtual User User { get; set; }
        public decimal ProgressInPercentes { get; set; }
    }
}
