//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string ProjectCode { get; set; }
        public string Assignee { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Description { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
